### ISSUE TITLE
SpotServe  does not contain the path docs/Appendix.pdf.

### ISSUE THREAD

**Issue by KevinCheung2259** [Hsword/SpotServe#9]
I find that SpotServe does not contain the path docs/Appendix.pdf. Can you provide information about this file? Thank you!

**Comment by Hsword** [comment]
You can find the Appendix in our [paper](https://dl.acm.org/doi/pdf/10.1145/3620665.3640411)

**Comment by KevinCheung2259** [comment]
已收到，谢谢！

**Comment by HanjiangWu313** [comment]
> 已收到，谢谢！

请问，我也想看一下在哪里，但是没有找到。请问可以指出一下在哪里吗？谢谢
